# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs;C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/build-final")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Users/ryair/scoop/apps/cmake/current/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "DarkThumbs built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/DarkThumbs")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "DarkThumbs 6.0.0")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "DarkThumbs")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "C:/Users/ryair/scoop/apps/llvm/current/bin/llvm-objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "C:/Users/ryair/scoop/apps/llvm/current/bin/llvm-objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/build-final/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/ryair/scoop/apps/cmake/current/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Advanced Thumbnail Generator for Windows")
set(CPACK_PACKAGE_FILE_NAME "DarkThumbs-6.0.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/yourusername/DarkThumbs")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "DarkThumbs")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "DarkThumbs")
set(CPACK_PACKAGE_NAME "DarkThumbs")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "DarkThumbs Project")
set(CPACK_PACKAGE_VERSION "6.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "6")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "C:/Users/ryair/scoop/apps/mingw/current/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Users/ryair/scoop/apps/cmake/current/share/cmake-4.2/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/build-final/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "DarkThumbs-6.0.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/ryair/OneDrive - Intel Corporation/Documents/MyScripts/DarkThumbs/build-final/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
