#Requires -Version 7.0
# ExplorerLens v7.0 - Build libavif 1.3.0 (AV1 Image Format)
# Refactored to use Build-Library-Core.ps1 module
# Date: February 18, 2026
#
# Directory structure (post-cleanup):
#   Project root:       <repo>\
#   This script:        <repo>\build-scripts\external-libs\Build-LibAVIF.ps1
#   Core module:        <repo>\build-scripts\core\Build-Library-Core.ps1
#   libavif source:     <repo>\external\image-libs\libavif-1.3.0\
#   dav1d install:      <repo>\external\image-libs\dav1d-1.5.1\install\
#   Build dir:          <repo>\external\image-libs\libavif-1.3.0\build-msvc\
#   Install dir:        <repo>\external\image-libs\libavif-1.3.0\install\

param(
    [string]$Configuration = "Release",
    [switch]$Clean
)

# Import core build module
. "$PSScriptRoot\..\core\Build-Library-Core.ps1"

$rootDir = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$sourceDir = Join-Path $rootDir "external\image-libs\libavif-1.3.0"
$dav1dDir = Join-Path $rootDir "external\image-libs\dav1d-1.5.1\install"
$zlibDir = Join-Path $rootDir "external\compression-libs\zlib-1.3.1\install"
$buildDir = Join-Path $sourceDir "build-msvc"
$installDir = Join-Path $sourceDir "install"

Write-BuildHeader "Building libavif 1.3.0 (AV1 Image Format)"

# Verify source directory
if (-not (Test-Path $sourceDir)) {
    Write-BuildLog "libavif-1.3.0 not found at $sourceDir" -Level Error
    Write-BuildLog "Please run download-all-libs.ps1 first" -Level Warning
    exit 1
}

# Verify dav1d dependency
if (-not (Test-Path (Join-Path $dav1dDir "lib\dav1d.lib"))) {
    Write-BuildLog "dav1d not built. Please run Build-Dav1d.ps1 first" -Level Error
    exit 1
}

Write-BuildLog "Source: $sourceDir" -Level Info
Write-BuildLog "Build: $buildDir" -Level Info
Write-BuildLog "Install: $installDir" -Level Info
Write-BuildLog "DAV1D: $dav1dDir" -Level Info
Write-BuildLog "ZLIB: $zlibDir" -Level Info

try {
    # Create dav1d CMake config for find_package(dav1d) discovery
    $dav1dCmakeDir = Join-Path $dav1dDir "lib\cmake\dav1d"
    New-Item -ItemType Directory -Path $dav1dCmakeDir -Force | Out-Null
    $dav1dIncDir = (Join-Path $dav1dDir "include").Replace('\', '/')
    $dav1dLibPath = (Join-Path $dav1dDir "lib\dav1d.lib").Replace('\', '/')
    @"
# dav1d CMake config - auto-generated by Build-LibAVIF.ps1
if(NOT TARGET dav1d::dav1d)
    add_library(dav1d::dav1d STATIC IMPORTED)
    set_target_properties(dav1d::dav1d PROPERTIES
        IMPORTED_LOCATION "$dav1dLibPath"
        INTERFACE_INCLUDE_DIRECTORIES "$dav1dIncDir"
    )
endif()
set(dav1d_FOUND TRUE)
"@ | Set-Content (Join-Path $dav1dCmakeDir "dav1dConfig.cmake") -Encoding UTF8

    # CMake options for libavif
    $cmakeOptions = @{
        'CMAKE_BUILD_TYPE'                          = 'Release'
        'BUILD_SHARED_LIBS'                         = 'ON'
        'AVIF_CODEC_DAV1D'                          = 'SYSTEM'
        'AVIF_LIBYUV'                               = 'ON'
        'CMAKE_PREFIX_PATH'                         = "$dav1dDir;$zlibDir"
        'AVIF_CODEC_AOM'                            = 'ON'
        'AVIF_BUILD_APPS'                           = 'ON'
        'AVIF_BUILD_TESTS'                          = 'ON'
        'AVIF_BUILD_EXAMPLES'                       = 'ON'
        'AVIF_ENABLE_EXPERIMENTAL_GAIN_MAP'         = 'ON'
        'AVIF_ENABLE_EXPERIMENTAL_SAMPLE_TRANSFORM' = 'ON'
    }
    
    # Build with CMake
    Invoke-CMakeBuild `
        -LibraryName "libavif" `
        -SourceDir $sourceDir `
        -BuildDir $buildDir `
        -InstallDir $installDir `
        -Configuration $Configuration `
        -CMakeOptions $cmakeOptions `
        -Clean:$Clean
    
    # Verify outputs
    $expectedLib = Join-Path $installDir "lib\avif.lib"
    Test-BuildOutput -Files @($expectedLib) -ThrowOnMissing
    
    Write-BuildLog "libavif 1.3.0 build completed successfully" -Level Success
    Write-BuildLog "Features: DAV1D decoder (AV1), Gain Map API (HDR), Sample Transform" -Level Info
    
} catch {
    Write-BuildLog "Build failed: $($_.Exception.Message)" -Level Error
    exit 1
}


