#pragma once

#include <vector>
#include <cstdint>

namespace ExplorerLens::Engine::AI::Stages {

    struct Rect {
        int x, y, width, height;
    };

    struct SaliencyMap {
        std::vector<float> heatMap; // Normalized 0.0-1.0
        uint32_t width;
        uint32_t height;
    };

    class ISmartCropStage {
    public:
        virtual ~ISmartCropStage() = default;

        // Given an image, return the best cropping rectangle for the target aspect ratio.
        // inputRaw: RGB/RGBA buffer
        virtual Rect CalculateCrop(const std::vector<uint8_t>& inputRaw, uint32_t width, uint32_t height, float targetAspectRatio) = 0;

        // Debugging: Get the saliency map generated by the model
        virtual SaliencyMap GenerateSaliency(const std::vector<uint8_t>& inputRaw, uint32_t width, uint32_t height) = 0;
    };

}

