#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MAINFRAME                           128
#define IDD_MAINDLG                             129
#define IDD_ABOUTBOX                            130
#define IDC_SORT_DESC                           1000
#define IDC_APPABOUT                            1001
#define IDC_APPLY                               1002
#define IDC_SORT_ADVOPTGROUP                    1003
#define IDC_CB_CBZ                              1004
#define IDC_TH_GROUP                            1005
#define IDC_CB_EPUB                             1006
#define IDC_CB_CBR                              1007
#define IDC_CB_CB7                              1008
#define IDC_CB_CBT                              1009
#define IDC_CB_SHOWICON                         1010
#define IDC_CB_SHOWICON_DESC                    1011
#define IDC_CB_ZIP                              1012
#define IDC_CB_RAR                              1013
#define IDC_CB_7Z                               1014
#define IDC_CB_TAR                              1015
#define IDC_CB_MOBI                             1016
#define IDC_CB_FB2                              1017
#define IDC_CB_AZW                              1018
#define IDC_CB_AZW3                             1019
#define IDC_CB_PHZ                              1020
#define IDC_CB_SORT                             1021
#define IDC_CB_WEBP                             1022
#define IDC_CB_HEIF                             1023
#define IDC_CB_AVIF                             1024
#define IDC_CB_JXL                              1025
#define IDC_CB_VIDEO                            1026
#define IDC_CB_PDF                              1027
#define IDC_CB_TIFF                             1040
#define IDC_CB_SVG                              1041
#define IDC_STATUSBAR                           1042
#define IDC_CB_RAW                              1043
#define IDC_BTN_THEME                           1044
#define IDC_COLLAGE_GROUP                       1028
#define IDC_RADIO_1X1                           1029
#define IDC_RADIO_2X2                           1030
#define IDC_RADIO_3X3                           1031
#define IDC_RADIO_4X4                           1032
#define IDC_COLLAGE_DESC                        1033
#define IDC_COMIC_GROUP                         1034
#define IDC_EBOOK_GROUP                         1035
#define IDC_ARCHIVE_GROUP                       1036
#define IDC_PHOTO_GROUP                         1037
#define IDC_IMAGE_GROUP                         1038
#define IDC_MEDIA_GROUP                         1039
#define IDD_CHANGE_SUMMARY                      131
#define IDC_LIST_CHANGES                        1050
#define IDC_EDIT_SUMMARY                        1051
#define IDC_EDIT_OPTIONS_CHANGES                1052
#define IDC_BTN_SAVE_CONFIG                     1053
#define IDC_BTN_RESTORE                         1054
#define IDC_BTN_LOAD_CONFIG                     1055
#define IDC_CB_PSD                              1056
#define IDC_CB_DDS                              1057
#define IDC_CB_HDR                              1058
#define IDC_CB_AUDIO                            1059
#define IDC_CB_DOCUMENT                         1060
#define IDC_CB_FONT                             1061
#define IDC_CB_EXR                              1062
#define IDC_PRO_IMAGE_GROUP                     1063
// Sprint 8: New format checkbox resource IDs
#define IDC_CB_ICO                              1064
#define IDC_CB_QOI                              1065
#define IDC_CB_PPM                              1066
#define IDC_CB_TGA                              1067
#define IDC_CB_MODEL                            1068
#define IDC_SPECIALIZED_GROUP                   1069

