// EngineTestsIncludes.h — Shared includes for split test files
// Copyright (c) 2026 ExplorerLens Project
//
// Auto-generated from EngineTests.cpp v33.0.0 split.
// All Engine header includes used by test files.
//
#pragma once

#include "../AI/SceneUnderstandingEngine.h"
#include "../AI/SmartCropV2.h"
#include "../Cache/CacheWarmingService.h"
#include "../Cache/MultiTenantCacheManager.h"
#include "../Cache/PersistentCacheManager.h"
#include "../Cache/PersistentDiskCache.h"
#include "../Cache/PipelineStateCacheV2.h"
#include "../Cache/SubMillisecondCacheEngine.h"
#include "../Core/AIThumbnailEnhancer.h"
#include "../Core/AccessibilitySuiteV2.h"
#include "../Core/AsyncShellActivation.h"
#include "../Core/AsyncShellExtension.h"
#include "../Core/BatchProcessingEngine.h"
#include "../Core/CloudStorageIntegration.h"
#include "../Core/CloudSyncProvider.h"
#include "../Core/Concepts.h"
#include "../Core/ContentIndexer.h"
#include "../Core/D3D12PipelineActivation.h"
#include "../Core/DiagnosticCollector.h"
#include "../Core/EncoderExportEngine.h"
#include "../Core/ErrorReportingPipeline.h"
#include "../Core/Expected.h"
#include "../Core/FormatConverterEngine.h"
#include "../Core/FormatRegistry.h"
#include "../Core/FormatTypes.h"
#include "../Core/GPUMemoryPoolV2.h"
#include "../Core/GPUPipelineV3.h"
#include "../Core/HDRDisplayPipeline.h"
#include "../Core/MetadataExtractor.h"
#include "../Core/MultiGPULoadBalancer.h"
#include "../Core/NetworkProviderEngine.h"
#include "../Core/ParallelBatchProcessor.h"
#include "../Core/PerMonitorDPIV3.h"
#include "../Core/PerformanceBenchmarkV2.h"
#include "../Core/PreviewPanelV2.h"
#include "../Core/ProgressiveThumbnailLoader.h"
#include "../Core/QuickLookIntegration.h"
#include "../Core/RegistryManager.h"
#include "../Core/ResourcePoolEngine.h"
#include "../Core/ResultType.h"
#include "../Core/RuntimeIntegrityVerifier.h"
#include "../Core/SIMDAccelerationManager.h"
#include "../Core/SIMDAccelerator.h"
#include "../Core/SecurityHardeningV2.h"
#include "../Core/ShaderCompilerV2.h"
#include "../Core/SharePointTeamsIntegration.h"
#include "../Core/ShellContextMenuV2.h"
#include "../Core/ShellOverlayHandler.h"
#include "../Core/ShellRegistrationManager.h"
#include "../Core/StructuredErrorDomain.h"
#include "../Core/TelemetryAnalyticsEngine.h"
// TelemetryEngine.h shim removed — Telemetry.h included below
#include "../Core/ThemeEngine.h"
#include "../Core/ThumbnailAnimationEngineV2.h"
#include "../Core/UpdateEngine.h"
#include "../Core/VersionSyncV14.h"
#include "../Core/VulkanComputeActivation.h"
#include "../Core/WatchFolderEngine.h"
#include "../Core/WinRTAppSDKIntegrationV2.h"
#include "../Decoders/ANIMDecoder.h"
#include "../Decoders/AVIFDecoder.h"
#include "../Decoders/Advanced3DFormatDecoder.h"
#include "../Decoders/AnimatedFormatHandler.h"
#include "../Decoders/ArchiveDecoder.h"
#include "../Decoders/AudioDecoder.h"
#include "../Decoders/AudioVisualizationV2.h"
#include "../Decoders/CADFormatDecoder.h"
#include "../Decoders/CURDecoder.h"
#include "../Decoders/DDSDecoder.h"
#include "../Decoders/DICOMDecoderV2.h"
#include "../Decoders/DPXDecoder.h"
#include "../Decoders/DatabasePreviewDecoder.h"
#include "../Decoders/DecoderSecurityHardening.h"
#include "../Decoders/DocumentDecoder.h"
#include "../Decoders/EBookDecoder.h"
#include "../Decoders/EPSDecoder.h"
#include "../Decoders/EXRDecoder.h"
#include "../Decoders/ExtendedVideoDecoder.h"
#include "../Decoders/FITSDecoderV2.h"
#include "../Decoders/FLIFDecoderV2.h"
#include "../Decoders/FontDecoder.h"
#include "../Decoders/GeospatialDecoder.h"
#include "../Decoders/HDRDecoder.h"
#include "../Decoders/HEIFDecoder.h"
#include "../Decoders/HRZDecoder.h"
#include "../Decoders/ICNSDecoder.h"
#include "../Decoders/ICODecoder.h"
#include "../Decoders/ImageDecoder.h"
#include "../Decoders/JPEG2000TileDecoderV2.h"
#include "../Decoders/JXLDecoder.h"
#include "../Decoders/KTXTextureDecoder.h"
#include "../Decoders/LegacyImageDecoder.h"
#include "../Decoders/MNGDecoder.h"
#include "../Decoders/Model3DRendererV2.h"
#include "../Decoders/ModelDecoder.h"
#include "../Decoders/ModelFormatHandler.h"
#include "../Decoders/NIfTIDecoder.h"
#include "../Decoders/NotebookPreviewDecoder.h"
#include "../Decoders/OpenRasterDecoder.h"
#include "../Decoders/PDFDecoder.h"
#include "../Decoders/PIXARDecoder.h"
#include "../Decoders/PPMDecoder.h"
#include "../Decoders/PSDDecoder.h"
#include "../Decoders/QOIDecoder.h"
#include "../Decoders/RAWDecoder.h"
#include "../Decoders/SGIDecoder.h"
#include "../Decoders/SVGDecoder.h"
#include "../Decoders/ScientificDataDecoder.h"
#include "../Decoders/SpreadsheetPreviewDecoder.h"
#include "../Decoders/StructuredDataDecoder.h"
#include "../Decoders/TextPreviewDecoder.h"
#include "../Decoders/USDDecoder.h"
#include "../Decoders/VTFDecoder.h"
#include "../Decoders/VectorFormatDecoder.h"
#include "../Decoders/VideoDecoder.h"
#include "../Decoders/WebPDecoder.h"
#include "../Decoders/XCFDecoder.h"
#include "../Decoders/XPMDecoder.h"
// Sprint 491-500 — Cross-Process Architecture (v24.1.0 "Altair-R")
#include "../Core/CrossProcEventBus.h"
#include "../Core/CrossProcessCacheProxy.h"
#include "../Core/OutOfProcThumbnailServer.h"
#include "../Core/ProcessIsolationPolicy.h"
#include "../Core/ProcessPoolManager.h"
#include "../Core/SharedStateCoordinator.h"
#include "../Engine.h"
#include "../GPU/D3D12ComputePipeline.h"
#include "../GPU/GPUDecodeAccelerationV2.h"
#include "../GPU/VulkanComputePipeline.h"
#include "../Memory/MemoryFootprintOptimizerV2.h"
#include "../Pipeline/AsyncThumbnailProvider.h"
#include "../Pipeline/DecoderRegistry.h"
#include "../Pipeline/FormatDetector.h"
#include "../Pipeline/ParallelBatchDecoder.h"
#include "../Pipeline/ParallelIOPipeline.h"
#include "../Pipeline/PipelineErrorBoundary.h"
#include "../Pipeline/RemoteRenderProxy.h"
#include "../Pipeline/SmartFormatDetectorV2.h"
#include "../Plugin/PluginLifecycle.h"
#include "../Plugin/PluginMarketplaceUnified.h"
#include "../Plugin/PluginPerformanceProfiler.h"
#include "../Plugin/PluginSDKV2.h"
#include "../Plugin/PluginSecurity.h"
#include "../Utils/AutoDocGenerator.h"
#include "../Utils/AutoUpdateEngine.h"
#include "../Utils/CIValidator.h"
#include "../Utils/CodeCoverageIntegration.h"
#include "../Utils/CommandLineInterface.h"
#include "../Utils/ConfigMigrationEngine.h"
#include "../Utils/DiagnosticDashboard.h"
#include "../Utils/EnterpriseDeploymentManager.h"
#include "../Utils/FileHashEngine.h"
#include "../Utils/FuzzingEngine.h"
#include "../Utils/InputValidator.h"
#include "../Utils/InstallerManager.h"
#include "../Utils/LogRotationEngine.h"
#include "../Utils/MalformedInputHandler.h"
#include "../Utils/MemorySafety.h"
#include "../Utils/MemorySafetyIntegration.h"
#include "../Utils/NetworkDiagnostics.h"
#include "../Utils/NotificationEngine.h"
#include "../Utils/PortableModeManager.h"
#include "../Utils/PythonSDK.h"
#include "../Utils/QualityGates.h"
#include "../Utils/ReleaseGate.h"
#include "../Utils/SecureAllocator.h"
#include "../Utils/SecurityCompliance.h"
#include "../Utils/TestFramework.h"
#include "../Utils/TestInfrastructure.h"
#include "../Utils/TestSuiteExpansion.h"
#include "../Utils/WindowsCompat.h"

// Sprint 1061-1070 — Intelligent Workflow Automation (v31.3.0 "Achernar-T")
#include "../AI/ContentCategorizationEngine.h"
#include "../AI/PredictivePregenEngine.h"
#include "../AI/ThumbnailQualityPredictor.h"
#include "../Core/SmartBatchProcessor.h"
#include "../Core/UserBehaviorAnalytics.h"
#include "../Core/WorkflowAutomationEngine.h"
#include "../Pipeline/AdaptivePipelineOptimizer.h"
#include "../Pipeline/IntelligentPrefetchScheduler.h"
// v31.9.0 — Autonomous Shell Intelligence
#include "../AI/AutonomousWorkflowOrchestrator.h"
#include "../AI/ShellIntelligenceAdapter.h"
#include "../AI/ThumbnailRelevanceRanker.h"
#include "../Core/AdaptiveShellIntegrationEngine.h"
#include "../Core/ShellExtensionLifecycleManager.h"
#include "../Pipeline/AutotuningPipelineEngine.h"
#include "../Utils/CrossPlatformBuildValidator.h"
// v32.0.0 — Post-Quantum Security & Zero-Trust
#include "../Core/BinaryTrustVerifier.h"
#include "../Core/PostQuantumCryptoProvider.h"
#include "../Core/QuantumResistantHashEngine.h"
#include "../Core/SecureConfigurationManager.h"
#include "../Core/ThreatModelingEngine.h"
#include "../Core/ZeroTrustAccessBroker.h"
#include "../Plugin/PluginZeroTrustSandbox.h"
#include "../Utils/SecurityPostureAnalyzer.h"
// v32.1.0 — Edge AI & Hardware-Accelerated Inference
#include "../AI/HardwareCapabilityNegotiator.h"
#include "../Core/ComputeDeviceRegistry.h"
#include "../GPU/AMDXDNABackend.h"
#include "../GPU/EdgeAIInferenceEngine.h"
#include "../GPU/IntelAMXBackend.h"
#include "../GPU/NPUAccelerationEngine.h"
#include "../GPU/QualcommAIEBackend.h"
#include "../Pipeline/HardwareAcceleratedPipeline.h"
// Sprint 1091-1100: DirectStorage & Zero-Latency Pipeline (v32.2.0 "Fomalhaut-S")
#include "../Core/DirectStorageManager.h"
#include "../Core/GPUDecompressKernel.h"
#include "../Core/StreamingDecodeOrchestrator.h"
#include "../Core/ThumbnailPipelineMetrics.h"
#include "../Pipeline/ZeroLatencyPipeline.h"
// Sprint 1101-1110: Annotation, HDR Tone Mapping & Format Detection (v32.3.0 "Fomalhaut-T")
#include "../Core/AdaptiveBitDepthConverter.h"
#include "../Core/FormatSignatureDetector.h"
#include "../Core/MemoryMappedDecoder.h"
#include "../Core/ThumbnailAnnotationOverlay.h"
#include "../Pipeline/BatchThumbnailExporter.h"
// Sprint 1111-1120: DirectStorage Zero-Copy GPU Decompress (v32.5.0 "Fomalhaut-V")
#include "../GPU/ZStdGPUKernel.h"
#include "../GPU/GPUDecompressOrchestrator.h"
#include "../Pipeline/DirectStorageBatchScheduler.h"
#include "../Core/DirectStorageProfiler.h"
#include "../Core/ZeroCopyDecodeSession.h"
// Sprint 1121-1130: CLIP Semantic Search + HNSW Index (v32.6.0 "Fomalhaut-W")
#include "../AI/HNSWIndexEngine.h"
#include "../AI/CLIPQueryProcessor.h"
#include "../AI/SemanticSearchOrchestrator.h"
#include "../AI/EmbeddingPersistenceEngine.h"
#include "../AI/VisualQueryOptimizer.h"
// Sprint 1131-1140: Live Preview Scrubber (v32.7.0 "Fomalhaut-X")
#include "../Media/VideoFrameExtractor.h"
#include "../Media/VideoScrubberTimeline.h"
#include "../Media/LivePreviewSession.h"
#include "../Media/ThumbnailStripGenerator.h"
#include "../Media/ScrubberCacheEngine.h"
// Platform (Windows-only)
#include "../Platform/PlatformShellProvider.h"
#include "../Platform/Win32ShellProvider.h"
#include "../Platform/PlatformDetector.h"
#include "../Platform/PlatformGPURouter.h"
// Sprint 1161-1170: Enterprise Console v4 (v33.2.0 "Spica-S")
#include "../Enterprise/EnterprisePolicyV4.h"
#include "../Enterprise/GPOPolicyTemplate.h"
#include "../Enterprise/IntuneComplianceEngine.h"
#include "../Enterprise/EnterpriseAuditLogger.h"
#include "../Enterprise/ConfigMgrPolicyBridge.h"
// Sprint 1171-1180: Generative AI Thumbnails (v33.3.0 "Spica-T")
#include "../AI/NPUThumbnailSynthesizer.h"
#include "../AI/DiffusionModelEngine.h"
#include "../AI/ThumbnailInpaintEngine.h"
#include "../AI/OffDeviceInferenceRouter.h"
#include "../AI/AIThumbnailBatchProcessor.h"
// Sprint 1181-1190: Plugin Marketplace v5 (v33.4.0 "Spica-U")
#include "../Plugin/PluginMarketplaceV5.h"
#include "../Plugin/SDKCompatKit3.h"
#include "../Plugin/PluginDistributionManager.h"
#include "../Plugin/MarketplaceSearchIndex.h"
#include "../Plugin/PluginSignatureValidator.h"
// Sprint 1191-1200: LTS Hardening + Security Audit (v33.5.0 "Spica-V")
#include "../Utils/LTSHardeningController.h"
#include "../Utils/SecurityAuditEngine.h"
#include "../Utils/VulnerabilityFingerprintDB.h"
#include "../Utils/LTSCertificationGate.h"
#include "../Utils/SecureKeyStore.h"
// Sprint 1201-1210: Format Coverage Blitz (v34.0.0 "Arcturus")
#include "../Decoders/BasisUniversalDecoder.h"
#include "../Decoders/UltraHDRDecoder.h"
#include "../Decoders/IfcBimDecoder.h"
#include "../Decoders/LasPointCloudDecoder.h"
#include "../Decoders/JupyterNotebookDecoder.h"

// Sprint 1211-1220: GPU-First Decode Pipeline (v34.1.0 "Arcturus-R")
#include "../GPU/GPUDecodeFormatRouter.h"
#include "../GPU/GPUJPEGDecodeAccelerator.h"
#include "../GPU/GPURawDemosaicKernel.h"
#include "../GPU/GPUDecodePerformanceGate.h"
#include "../GPU/ZeroCopyGPUSurface.h"

// Sprint 1221-1230: HDR & Wide Color Gamut Mastery (v34.2.0 "Arcturus-S")
#include "../Core/GainmapJPEGToneMapper.h"
#include "../Core/PQToSDRToneMapper.h"
#include "../Core/HLGToSDRConverter.h"
#include "../Core/ICCv5ProfileEngine.h"
#include "../Core/ACESODTProcessor.h"

// Sprint 1231-1240: Predictive Pre-Generation Engine (v34.3.0 "Arcturus-T")
#include "../Pipeline/DirectoryPreScanQueue.h"
#include "../Pipeline/AdjacencyPredictor.h"
#include "../Pipeline/ScrollVelocityTracker.h"
#include "../Pipeline/IdleTimePreGenerator.h"
#include "../Pipeline/PredictivePreGenEngine.h"

// Sprint 1241-1250: Animated & Sequence Format Suite (v34.4.0 "Arcturus-U")
#include "../Core/HoverScrubController.h"
#include "../Core/APNGFrameCombiner.h"
#include "../Decoders/GIFAnimationDecoder.h"
#include "../Decoders/AnimatedSequenceSampler.h"
#include "../Cache/AnimatedThumbnailCache.h"

// Sprint 1251-1260: Industrial & Scientific Formats v2 (v34.5.0 "Arcturus-V")
#include "../Decoders/DICOMWindowingPresets.h"
#include "../Decoders/FITSZScaleStretch.h"
#include "../Decoders/LASPointCloudRenderer.h"
#include "../Decoders/OMETIFFCompositor.h"
#include "../Decoders/MHAVolumeDecoder.h"

// Sprint 1261-1270: CAD/BIM/EDA Formats (v34.6.0 "Arcturus-W")
#include "../Decoders/DWGHeaderParser.h"
#include "../Decoders/STEPBoundingBoxExtractor.h"
#include "../Decoders/IFCEntityCounter.h"
#include "../Decoders/GerberLayerCompositor.h"
#include "../Decoders/KiCadNetlistParser.h"

// Sprint 1271-1280: Performance Hardening + LTS Gate (v34.7.0 "Arcturus-X")
#include "../Core/PerfRegressionGate.h"
#include "../Core/LTSBuildValidator.h"
#include "../Cache/CacheWarmupPreloader.h"
#include "../Pipeline/DecodeLatencyProfiler.h"
#include "../Utils/BenchmarkBaseline.h"

// Sprint 1281-1290: Streaming & Cloud-Native Thumbnails (v35.0.0 "Vega")
#include "../Pipeline/MultiStageThumbnailEmitter.h"
#include "../Core/CloudHydrationMonitor.h"
#include "../Cache/PartialDecodeStateCache.h"
#include "../Core/ThumbnailETagValidator.h"
#include "../Pipeline/AdaptiveFidelitySelector.h"

// Sprint 1291-1300: Real-Time Collaboration & Live Edit Sync (v35.1.0 "Vega-R")
#include "../Core/LiveSyncTokenManager.h"
#include "../Cache/CollaborativeCacheCoordinator.h"
#include "../Pipeline/ThumbnailDeltaEncoder.h"
#include "../Core/ConflictResolutionEngine.h"
#include "../Pipeline/RealTimePreviewPipeline.h"
// Sprint 1301-1310: Network-Aware Streaming Cache
#include "../Core/NetworkTopologyProbe.h"
#include "../Cache/StreamingCacheTierPolicy.h"
#include "../Pipeline/BandwidthThrottleGuard.h"
#include "../Cache/RemoteFileManifestCache.h"
#include "../Cache/CachePrefetchScheduler.h"
// Sprint 1311-1320: Zero-Trust Thumbnail Security
#include "../Core/ThumbnailManifestSigner.h"
#include "../Pipeline/ZeroTrustDecodeWorker.h"
#include "../Cache/TokenBoundCacheEntry.h"
#include "../Core/ThumbnailAuditLog.h"
#include "../Core/FIPSCryptoAdapter.h"
// Sprint 1321-1330: WebAssembly / Browser Extension Pipeline
#include "../Core/WasmDecoderShim.h"
#include "../Pipeline/BrowserThumbnailBridge.h"
#include "../Pipeline/OffscreenCanvasRenderer.h"
#include "../Cache/WasmCacheAdapter.h"
#include "../Pipeline/ProgressiveThumbnailStream.h"
// Sprint 1331-1340: Cross-Device Preview Sync
#include "../Core/DeviceSyncManifest.h"
#include "../Cache/CrossDeviceCacheSync.h"
#include "../Pipeline/ThumbnailPackFile.h"
#include "../Core/SyncConflictResolver.h"
#include "../Core/DeviceCapabilityAdvertiser.h"

// Sprint 47-48: CI/CD Pipeline + Build Validation
#include "../Utils/BuildValidator.h"
#include "../Utils/CITestReporter.h"
#include "../Utils/EnvironmentProbe.h"

// ===== Feature Module Includes =====

// --- Feature Module Integrations ---
#include "../Core/ArchiveRefactorEngine.h"
#include "../Core/FFmpegIntegration.h"
#include "../Core/FreeTypeIntegration.h"
#include "../Core/LibWebPConfig.h"
#include "../Core/LibraryVersionAudit.h"
#include "../Core/MuPDFIntegration.h"
#include "../Core/OpenJPEGIntegration.h"

// --- Memory Management ---
#include "../Memory/BitmapPool.h"

// --- Shell Integration ---
#include "../Core/GPUShaderLibrary.h"
#include "../Core/PerformanceDashboard.h"
#include "../Core/PluginHostManager.h"
#include "../Core/PropertyStoreHandler.h"
#include "../Core/SettingsExportImport.h"

// --- Observability & DevOps ---
#include "../Core/CIHardeningEngine.h"
#include "../Core/CodeCoverageEngine.h"
#include "../Core/ETWTraceProvider.h"

// --- UI & Theming ---
#include "../Core/DarkModeRendererV2.h"
#include "../Core/HybridUIBridge.h"
#include "../Core/SystemTrayManager.h"
#include "../Core/WinUI3MigrationEngine.h"
#include "../Core/WinUI3Research.h"

// --- Test Infrastructure ---
#include "../Utils/ContinuousFuzzOrchestrator.h"
#include "../Utils/IntegrationTestFrameworkV2.h"
#include "../Utils/IntegrationTestOrchestrator.h"
#include "../Utils/StaticAnalysisCIGate.h"

// --- Documentation ---
#include "../Core/DocumentationSyncAudit.h"

// --- Pipeline & Performance ---
#include "../Pipeline/ZeroCopyPipeline.h"
#include "../Utils/SIMDScaler.h"

#include "../Core/LivePreviewScrubber.h"
// --- Sprint additions: stub headers for missing types ---
#include "../AI/AISearchIntegration.h"
#include "../AI/ContentAwareInpainter.h"
#include "../AI/GenerativeThumbnailEngine.h"
#include "../AI/ImageDescriptionSynthesizer.h"
#include "../AI/StyleTransferRenderer.h"
#include "../Core/DarkModeEngine.h"
#include "../Core/DecoderCompatLayer.h"
#include "../Core/DecoderHotfixApplicator.h"
#include "../Core/DecoderVersionRegistry.h"
#include "../Core/FormatCapabilityMatrix.h"
#include "../Core/FormatCategoryManager.h"
#include "../Core/FormatFamilyResolver.h"
#include "../Core/FormatSchemaValidator.h"
#include "../Core/FormatStatusIndicator.h"
#include "../Plugin/PluginDebuggerIntegration.h"
#include "../Plugin/PluginHotReload.h"
#include "../Utils/DocumentationExcellenceV2.h"
// --- Sprint 991-1060: core, decoders, AI, plugin, enterprise additions ---
#include "../AI/CLIPEmbeddingEngine.h"
#include "../AI/ContentModerationFilter.h"
#include "../AI/EmbeddingCacheStore.h"
#include "../AI/GenerativeAuditTrail.h"
#include "../AI/GenerativeUpscalerV3.h"
#include "../AI/IncrementalIndexUpdater.h"
#include "../AI/MultiModalRanker.h"
#include "../AI/NaturalLanguageQueryParser.h"
#include "../AI/SearchResultDeduplicator.h"
#include "../AI/ThumbnailPersonalisationEngine.h"
#include "../Cache/DirectStorageCacheTier.h"
#include "../Core/AnimatedFrameScrubber.h"
#include "../Core/AnnotationExportPipelineV2.h"
#include "../Core/AnnotationSignatureVerifier.h"
#include "../Core/AnnotationTaxonomyV2.h"
#include "../Core/AnnotationTimeline.h"
#include "../Core/AsyncFileStreamBroker.h"
#include "../Core/AudioWaveformRenderer.h"
#include "../Core/CodecNegotiationProtocol.h"
#include "../Core/ColdStartFolderBootstrapper.h"
#include "../Core/CollaborativeAnnotationEngineV2.h"
#include "../Core/DocumentPagePreviewer.h"
#include "../Core/FolderPredictionModel.h"
#include "../Core/FontGlyphSampler.h"
#include "../Core/GRPCProtocolServerV2.h"
#include "../Core/GraphQLSchemaIntrospector.h"
#include "../Core/GraphQLSubscriptionServer.h"
#include "../Core/JWTValidationEngine.h"
#include "../Core/KDEDolphinExtension.h"
#include "../Core/LinuxNautilusExtension.h"
#include "../Core/LinuxThumbnailerDaemon.h"
#include "../Core/MacOSLaunchServicesAdapter.h"
#include "../Core/MacOSQuickLookV3.h"
#include "../Core/NativeFilesystemAdapter.h"
#include "../Core/NeuralCodecV2Engine.h"
#include "../Core/NeuralContainerFormat.h"
#include "../Core/OAuth2PKCEMiddleware.h"
#include "../Core/OfflineAnnotationSyncQueue.h"
#include "../Core/OpenAPICodeGenerator.h"
#include "../Core/PerUserPredictionIsolator.h"
#include "../Core/PlatformAbstractionLayer.h"
#include "../Core/PredictionAccuracyTracker.h"
#include "../Core/PredictionScanOrchestrator.h"
#include "../Core/PresenceIndicatorEngine.h"
#include "../Core/ProgressiveNeuralDecoder.h"
#include "../Core/RESTAPIServerV2.h"
#include "../Core/RateLimitingMiddleware.h"
#include "../Core/ShaderSyntaxHighlighter.h"
#include "../Core/SpreadsheetChartRenderer.h"
#include "../Core/ThunarThumbnailExtension.h"
#include "../Core/UniversalDecoderFacade.h"
#include "../Core/UniversalLibraryManifest.h"
#include "../Core/VideoKeyframeExtractor.h"
#include "../Core/WaylandShellExtension.h"
#include "../Core/XPlatformTestHarness.h"
#include "../Decoders/DICOMAdvancedDecoder.h"
#include "../Decoders/ECWDecoder.h"
#include "../Decoders/GeoTIFFDecoder.h"
#include "../Decoders/HDF5ThumbnailDecoder.h"
#include "../Decoders/NITFDecoder.h"
#include "../Decoders/NRRDDecoder.h"
#include "../Decoders/NetCDFDecoder.h"
#include "../Enterprise/ComplianceReportGenerator.h"
#include "../Enterprise/EnterpriseAuditExporter.h"
#include "../Enterprise/EnterpriseConsoleV3.h"
#include "../Enterprise/EnterpriseMetricsDashboard.h"
#include "../Enterprise/FleetDeploymentManager.h"
#include "../Enterprise/PolicyVersionControl.h"
#include "../Enterprise/RemoteDecoderControl.h"
#include "../Enterprise/UsageAnomalyDetector.h"
#include "../GPU/AMDDecompressBackend.h"
#include "../GPU/DMADirectPreloader.h"
#include "../GPU/DirectStorageEngine.h"
#include "../GPU/GPUDecompressScheduler.h"
#include "../GPU/NeuralCodecHWAccelerator.h"
#include "../GPU/NvGDeflateBackend.h"
#include "../GPU/StagingBufferPoolV2.h"
#include "../Pipeline/DirectStoragePipelineStage.h"
#include "../Plugin/AutoUpdatePolicyV4.h"
#include "../Plugin/MarketplaceClientV4.h"
#include "../Plugin/PluginBundleInstaller.h"
#include "../Plugin/PluginDependencyGraph.h"
#include "../Plugin/PluginRatingEngine.h"
#include "../Plugin/PluginReputationScorer.h"
#include "../Plugin/PrePublishReviewGateway.h"
#include "../Plugin/SubscriptionLicenseManagerV4.h"
#include "../Utils/PlatformBuildMatrix.h"

// --- Sprint 43-44: Plugin SDK Hardening ---
#include "../Plugin/PluginAuditLog.h"
#include "../Plugin/PluginCapabilityGuard.h"
#include "../Plugin/PluginVersionNegotiator.h"

// --- Sprint 41-42: Performance Tuning ---
#include "../Cache/CacheLinePadding.h"
#include "../Core/AlignedBufferPool.h"
#include "../Core/BranchPredictor.h"
#include "../Core/PrefetchHintEngine.h"
#include "../Pipeline/LoopTuner.h"

// --- Core Features ---
#include "../Core/AdaptiveDecoderRouter.h"
// TelemetryPipeline.h — consolidated into Telemetry.h
#include "../Core/CloudNativeSync.h"
#include "../Core/LivePreviewEngine.h"
// #include "../Cache/CacheEfficiencyAnalyzer.h" // Removed: header no longer exists
#include "../Core/AnimatedFormatController.h"
#include "../Core/CertificateTrustValidator.h"
#include "../Core/ColorSpaceEngine.h"
#include "../Core/ContentAwareThumbnailSelector.h"
#include "../Core/ContentInspectionGateway.h"
#include "../Core/DiagnosticReportGeneratorV2.h"
#include "../Core/DirectStorage12Integration.h"
#include "../Core/DocumentLayoutAnalyzer.h"
#include "../Core/EncryptedFormatHandler.h"
#include "../Core/FaceDetectionOrientation.h"
#include "../Core/GPUTextureCompressionPipeline.h"
#include "../Core/HDRToneMappingPipeline.h"
#include "../Core/HealthCheckEndpoint.h"
#include "../Core/LivePreviewStreamingProtocol.h"
#include "../Core/MetadataExtractionPipeline.h"
#include "../Core/MultiPageNavigator.h"
#include "../Core/NestedArchivePreview.h"
#include "../Core/NeuralTextureCompression.h"
#include "../Core/PerformanceAnomalyDetector.h"
#include "../Core/PreviewTooltipRenderer.h"
#include "../Core/QuantumReadyHashPipeline.h"
#include "../Core/QuickActionsOverlay.h"
#include "../Core/RoleBasedFormatPolicy.h"
#include "../Core/RustFFIBridge.h"
#include "../Core/SelfHealingDecoder.h"
#include "../Core/SmartQualityPredictor.h"
#include "../Core/SystemResourceMonitor.h"
// TelemetryPipelineV2.h — consolidated into Telemetry.h
#include "../Core/ThumbnailBatch.h"
#include "../Core/ThumbnailQuality.h"
#include "../Core/ThumbnailRenderer.h"
#include "../Core/ThumbnailStream.h"
#include "../Core/UsageAnalyticsDashboard.h"
#include "../Core/VirtualFilesystemAbstraction.h"
#include "../Core/VisualSimilarityIndex.h"
#include "../Core/WASMDecoderSandbox.h"
#include "../Core/WindowsSearchProtocol.h"
#include "../GPU/GPUTextureAtlasManager.h"
#include "../GPU/WebGPUThumbnailRenderer.h"
#include "../Pipeline/LockFreeDecodePipeline.h"
#include "../Pipeline/MemoryMappedIOOptimizer.h"
#include "../Pipeline/PredictivePrefetchEngine.h"
#include "../Pipeline/ShellProgressIndicator.h"
#include "../Pipeline/ThreadPoolOptimizer.h"

// --- Shell Deep Integration ---
#include "../Core/JumpListIntegration.h"

// --- Plugin System ---
#include "../Plugin/PluginLoaderV2.h"

// --- Streaming & SIMD ---
#include "../Pipeline/SIMDDispatchRouter.h"
#include "../Pipeline/StreamingDecodeEngine.h"
#include "../Pipeline/ZeroCopyActivation.h"

// --- GPU Compute ---
#include "../GPU/AdaptiveGPUScheduler.h"
#include "../GPU/HDRToneMapKernel.h"
#include "../GPU/LanczosGPUKernel.h"

// --- Cache Layer ---
#include "../Cache/PSOPersistenceManager.h"
#include "../Cache/PredictiveCacheEngine.h"

// --- Shell & Decoders ---
#include "../Core/DragDropThumbnailPreview.h"
#include "../Decoders/AnimatedImageDecoder.h"
#include "../Decoders/MultiPageStripRenderer.h"
#include "../Decoders/ProgressiveJPEGDecoder.h"

// --- Batch Processing & Validation ---
#include "../Core/SearchFederatedProvider.h"
#include "../Core/TaskbarPreviewManager.h"

// --- Optimization & Power ---
#include "../Utils/PowerThrottleManager.h"
#include "../Utils/RemoteDesktopOptimizer.h"

// --- GPU Sampling & Compilation ---
#include "../GPU/AsyncTextureSampler.h"
#include "../GPU/ShaderCacheCompiler.h"

// --- Format Detection & Storage ---
#include "../Memory/SmartPointerPool.h"
#include "../Pipeline/FormatSignatureDetector.h"

// --- File Integrity & Monitoring ---
#include "../Core/COMDiagnosticsEngine.h"
#include "../Core/CompressionBenchmark.h"
#include "../Core/ExplorerBandIntegration.h"
#include "../Core/FileIntegrityMonitor.h"
#include "../Core/HotReloadConfigEngine.h"
#include "../Core/IntelligentPrefetchV2.h"
#include "../GPU/GPUWorkloadBalancer.h"
#include "../Pipeline/FilesystemWatchdog.h"
#include "../Utils/RegistrySnapshotManager.h"

// --- Watermark & Annotation ---
#include "../Cache/CacheMigrationEngine.h"
#include "../Core/BatchRenamePreview.h"
#include "../Core/DuplicateFileDetector.h"
#include "../Core/ExplorerContextMenuExtension.h"
#include "../Core/FileTypeStatistics.h"
#include "../Memory/MemoryDefragmenter.h"
#include "../Pipeline/AdaptiveQualityScaler.h"

// --- Version Control & Preview ---
#include "../Cache/CacheEncryptionLayer.h"
#include "../Core/AccessTokenValidator.h"
#include "../Core/ClipboardThumbnailManager.h"
#include "../Core/EnterpriseAuditPipeline.h"
#include "../Core/ExplorerPreviewPane.h"
#include "../Core/FilePreviewRouter.h"
#include "../Core/FormatConversionPipeline.h"
#include "../Core/ResourceQuotaManager.h"
#include "../GPU/VulkanMemoryAllocator.h"

// --- DirectShow & Health ---
#include "../Core/DirectShowThumbnailBridge.h"
#include "../Core/ExifOrientationFixer.h"
#include "../Core/FileAssociationManager.h"
#include "../Core/WindowsSearchIntegration.h"
#include "../GPU/DX12FenceManager.h"
#include "../Memory/VirtualAllocOptimizer.h"
#include "../Pipeline/AsyncIOCompletionEngine.h"

// --- Scheduler, Color, DPI, Histogram, Locale, Sprite, Telemetry ---
#include "../Cache/AdaptiveCacheBudgetManager.h"
#include "../Cache/CacheKeyGenerator.h"
#include "../Cache/CacheTelemetryCollector.h"
#include "../Core/CRTConsistencyManager.h"
#include "../Core/DeadCodeAudit.h"
#include "../Core/DeadCodeAuditor.h"
#include "../Core/DecoderPriorityScheduler.h"
#include "../Core/DiagnosticsExporter.h"
#include "../Core/ETWSinkComplete.h"
#include "../Core/ErrorContext.h"
#include "../Core/MultiMonitorDPIScaler.h"
#include "../Core/PerfRegressionGate.h"
#include "../Core/PerformanceActivation.h"
#include "../Core/ProgramClosureV83.h"
#include "../Core/ReleaseReadinessDashboard.h"
#include "../Core/ReproducibleBuildVerifier.h"
#include "../Core/ThumbnailColorSpace.h"
#include "../Core/ThumbnailHistogram.h"
#include "../Core/ThumbnailSpriteSheet.h"
#include "../Core/VersionDriftDetector.h"
#include "../Core/VersionDriftGate.h"
#include "../Memory/ArchiveMemoryCompactor.h"
#include "../Memory/BufferPoolAllocator.h"
#include "../Memory/DecoderHotsetManager.h"
#include "../Memory/DirectoryFormatProfiler.h"
#include "../Memory/HotModeDirectoryEngine.h"
#include "../Memory/MemoryOptimizationEngine.h"
#include "../Memory/MemoryPressureControllerV2.h"
#include "../Memory/MemorySoakValidator.h"
#include "../Pipeline/BatchProcessor.h"
#include "../Pipeline/ExplorerWorkScheduler.h"
#include "../Plugin/IsolationModeSelector.h"
#include "../Plugin/PluginActivation.h"
#include "../Plugin/PluginCompatibilityKitV2.h"
#include "../Plugin/PluginHostBridge.h"
#include "../Plugin/PluginHostClient.h"
#include "../Utils/AuditLogger.h"
#include "../Utils/CIPipeline.h"
#include "../Utils/CodeCoverage.h"
#include "../Utils/DecoderCircuitBreaker.h"
#include "../Utils/EXIFOrientation.h"
#include "../Utils/PerformanceProfiler.h"
#include "../Utils/ShellExtensionHealthMonitor.h"
#include "../Utils/SmallObjectPool.h"
#include "../Utils/ValidationHelpers.h"

#include "../Cache/MultiTierCache.h"
#include "../Cache/ThumbnailCache.h"
#include "../Cache/USNCacheInvalidation.h"
#include "../Codec/CodecLoader.h"
#include "../Codec/CodecModuleSpecs.h"
#include "../Codec/FormatConverter.h"
#include "../Core/BuildValidation.h"
#include "../Core/Config.h"
#include "../Core/EngineAPI.h"
#include "../Core/LibraryInventoryManager.h"
#include "../Core/ObservabilityIntegration.h"
#include "../Core/PluginTypes.h"
#include "../Core/Telemetry.h"
// TelemetryDashboard.h shim removed — Telemetry.h provides all telemetry types
#include "../Core/Types.h"
#include "../Core/VideoCodecRouter.h"
#include "../Decoders/ArchiveGridPreview.h"
#include "../Decoders/ColorSpaceManager.h"
#include "../Decoders/EBookCoverExtractor.h"
#include "../Decoders/JPEG2000Decoder.h"
#include "../Decoders/JXRWICDecoder.h"
#include "../Decoders/PCXDecoder.h"
#include "../Pipeline/ThumbnailPipeline.h"
#include "../Plugin/PluginManager.h"
#include "../Utils/HardwareCapabilities.h"
#include "../Utils/PerceptualHashing.h"

// Additional module headers
#include "../AI/ImageQualityAssessorV2.h"
#include "../Core/DiagnosticsCollector.h"
#include "../Core/IntegrationTestRunner.h"
#include "../Core/SBOMGenerator.h"
#include "../Plugin/PluginHotReloadManager.h"
#include "../Plugin/PluginNamedPipeBridge.h"
#include "../Plugin/PluginTrustChainValidator.h"
#include "../Utils/DocumentationGenerator.h"
#include "../Utils/InstallerLifecycleManager.h"

// Additional module headers
#include "../AI/DecodeStrategyOptimizer.h"
#include "../AI/ImageComplexityAnalyzer.h"
#include "../Cache/CacheBudgetAutoTuner.h"
#include "../Cache/CacheCoherencyManager.h"
#include "../Cache/CacheDiagnostics.h"
#include "../Cache/CachePrewarmScheduler.h"
#include "../Cache/PSOCachePersistence.h"
#include "../Core/AdaptiveContrastEnhancer.h"
#include "../Core/ArchiveHierarchyMapRenderer.h"
#include "../Core/ArchivePasswordDetector.h"
#include "../Core/AudioSpectrogramRenderer.h"
#include "../Core/BatchProgressReporter.h"
#include "../Core/BatchThumbnailOrchestrator.h"
#include "../Core/CacheCoherencyProtocol.h"
#include "../Core/CalendarHeatmapRenderer.h"
#include "../Core/ClipboardMonitorIntegration.h"
#include "../Core/CodeSyntaxThumbnail.h"
#include "../Core/ColorHistogramBadge.h"
#include "../Core/CompressedStreamAnalyzer.h"
#include "../Core/ContentAwareThumbnail.h"
#include "../Core/DecodeLatencyHistogram.h"
#include "../Core/DecoderRegistryV2.h"
#include "../Core/DocumentDigestOverlay.h"
#include "../Core/DominantColorExtractor.h"
#include "../Core/ExplorerStatusBarProvider.h"
#include "../Core/FileAgeVisualizer.h"
#include "../Core/FileSignatureDetector.h"
#include "../Core/FileSizeProportionBadge.h"
#include "../Core/FileSummaryTooltipGenerator.h"
#include "../Core/FontGlyphGridRenderer.h"
#include "../Core/GPUResourcePoolManager.h"
#include "../Core/GeoTagMapThumbnail.h"
#include "../Core/HealthScoreAggregator.h"
#include "../Core/InputSanitizer.h"
#include "../Core/IntelligentCachePruner.h"
#include "../Core/MetadataTooltipRenderer.h"
#include "../Core/PathTraversalGuard.h"
#include "../Core/PerceptualHashEngine.h"
#include "../Core/PerformanceRegressionDetector.h"
#include "../Core/PhotoMosaicThumbnail.h"
#include "../Core/PresentationSlideStrip.h"
#include "../Core/ResourceUsageProfiler.h"
#include "../Core/RuntimeSIMDDispatcher.h"
#include "../Core/SIMDCapabilityDetector.h"
#include "../Core/SmartGridLayoutEngine.h"
#include "../Core/SpreadsheetCellPreview.h"
#include "../Decoders/APNGDecoder.h"
#include "../Decoders/BPGDecoder.h"
#include "../Decoders/BrotliStreamInspector.h"
#include "../Decoders/COLLADADecoder.h"
#include "../Decoders/CertificateViewer.h"
#include "../Decoders/DiskImagePreview.h"
#include "../Decoders/FBXInspector.h"
#include "../Decoders/FLIFDecoder.h"
#include "../Decoders/LZ4FrameDecoder.h"
#include "../Decoders/LaTeXPreviewDecoder.h"
#include "../Decoders/MIDIVisualizer.h"
#include "../Decoders/MSIPackageInspector.h"
#include "../Decoders/MarkdownPreviewRenderer.h"
#include "../Decoders/RGBEDecoder.h"
#include "../Decoders/RTFDecoder.h"
#include "../Decoders/RegistryExportViewer.h"
#include "../Decoders/ShortcutInspector.h"
#include "../Decoders/SnappyFrameDecoder.h"
#include "../Decoders/SourceCodeThumbnail.h"
#include "../Decoders/SpectrogramRenderer.h"
#include "../Decoders/StructuredDataVisualizer.h"
#include "../Decoders/SubtitlePreviewDecoder.h"
#include "../Decoders/VideoTimelineStrip.h"
#include "../Decoders/WaveformGenerator.h"
#include "../Decoders/WebP2Decoder.h"
#include "../Decoders/XZStreamDecoder.h"
#include "../Decoders/ZstdFrameDecoder.h"
#include "../GPU/GPUFallbackChain.h"
#include "../GPU/GPUMemoryTracker.h"
#include "../Memory/AllocationTracker.h"
#include "../Memory/MemoryBudgetEnforcer.h"
#include "../Pipeline/AsyncPrefetchQueue.h"
#include "../Pipeline/DecodeMemoizationEngine.h"
#include "../Pipeline/DecodeRetryPolicy.h"
#include "../Pipeline/DecoderOutputValidator.h"
#include "../Pipeline/MemoryMappedDecodePath.h"
#include "../Pipeline/ParallelIOActivation.h"
#include "../Pipeline/PipelineActivator.h"
#include "../Pipeline/PipelineCircuitBreaker.h"
#include "../Pipeline/PipelineMetricsCollector.h"
#include "../Pipeline/ProductionPipelineV2.h"
#include "../Pipeline/ThreadLocalBufferPool.h"
#include "../Pipeline/ThumbnailRequestValidator.h"
#include "../Plugin/PluginCrashRecovery.h"
#include "../Plugin/PluginDependencyResolver.h"
#include "../Plugin/PluginResourceLimiter.h"
#include "../Utils/ConfigDriftDetector.h"
#include "../Utils/MemoryMappedFile.h"
#include "../Utils/OperationalReadinessChecker.h"
#include "../Utils/VersionNormalization.h"

// --- Sprint 37-38: Test Coverage Expansion ---
#include "../Core/VersionSynchronizer.h"

// --- Sprint 49-50: Dark Mode & Theme Rendering ---
#include "../Core/AdaptiveIconRenderer.h"
#include "../Core/ContrastValidator.h"
#include "../Core/SystemThemeMonitor.h"
#include "../Core/ThemeAwareOverlay.h"

// --- Sprint 51-52: Decode Pipeline Enhancement ---
#include "../Core/MultiPagePreview.h"
#include "../Core/StreamingDecodeEngine.h"

// --- Sprint 53-54: Memory Management ---
#include "../Memory/LargePageAllocator.h"
#include "../Memory/MemoryArenaAllocator.h"

// --- Sprint 55-56: Pipeline Scheduling ---
#include "../Pipeline/AdaptiveTimeoutController.h"
#include "../Pipeline/DecodePriorityQueue.h"
#include "../Pipeline/PipelineReplayRecorder.h"
#include "../Pipeline/PipelineStageProfiler.h"

// --- Sprint 57-58: Cache Intelligence ---
#include "../Cache/CacheCompressionEngine.h"
#include "../Cache/CacheIntegrityVerifier.h"

// --- Sprint 59-60: GPU Enhancement ---
#include "../GPU/GPUAsyncCopyEngine.h"
#include "../GPU/GPUDebugLayer.h"
#include "../GPU/GPUMemoryPoolManager.h"
#include "../GPU/GPUOccupancyOptimizer.h"
#include "../GPU/GPUShaderCompiler.h"

// --- Sprint 61-62: Enterprise & Deployment ---
#include "../Utils/DeploymentHealthChecker.h"
#include "../Utils/DiagnosticBundleExporter.h"
#include "../Utils/EnterpriseTelemetryRouter.h"
#include "../Utils/PolicyComplianceValidator.h"
#include "../Utils/SilentUpdateOrchestrator.h"

// --- Sprint 63-64: Plugin Ecosystem ---

// --- Sprint 65-66: Quality & Observability ---
#include "../Core/HealthCheckOrchestrator.h"
#include "../Core/ResourceLeakTracker.h"
#include "../Core/StructuredDiagnosticLogger.h"

// --- Sprint 67-68: Final Polish ---
#include "../Core/ColorSpaceConverter.h"
#include "../Core/CrashRecoveryEngine.h"
#include "../Core/ExifOrientationHandler.h"
#include "../Core/GracefulDegradationController.h"
#include "../Core/HDRToneMapper.h"
#include "../Core/IconBadgeRenderer.h"
#include "../Core/ShellIntegrationValidator.h"
#include "../Core/StartupOptimizer.h"
#include "../Core/UserPreferenceEngine.h"

// Sprint 9-14 (v15.3.0 "Zenith-T") — Resilience & Hardening
#include "../Core/ArchiveSecurityValidator.h"
#include "../Core/DecodeErrorCategory.h"
#include "../Core/DecodeInputValidator.h"
#include "../Core/GracefulDegradation.h"

// Sprint 69-88: Beyond Zenith
#include "../AI/FaceDetectionThumbnail.h"
#include "../AI/ObjectSaliencyMapper.h"
#include "../Cache/SemanticCacheIndex.h"
#include "../Core/AdaptiveLODEngine.h"
#include "../Core/ContentAwareCompositor.h"
#include "../Core/DistributedRenderEngine.h"
#include "../Core/HDRDisplayMapper.h"
#include "../Core/NeuralThumbnailUpscaler.h"
#include "../Core/QuantumSafeHasher.h"
#include "../Core/RealTimeCodecTranscoder.h"
#include "../Core/SemanticFileClassifier.h"
#include "../Core/VolumetricPreviewEngine.h"
#include "../Decoders/AlembicDecoder.h"
#include "../Decoders/GeospatialTileDecoder.h"
#include "../Decoders/HDRIEnvironmentDecoder.h"
#include "../Decoders/MaterialXDecoder.h"
#include "../Decoders/NeuralRadianceDecoder.h"
#include "../Decoders/NotationDecoder.h"
#include "../Decoders/OpenEXRDecoder.h"
#include "../Decoders/PCBLayoutDecoder.h"
#include "../Decoders/PointCloudStreamDecoder.h"
#include "../Decoders/VDBVolumeDecoder.h"
#include "../GPU/DirectStorageIntegration.h"
#include "../GPU/GPUDecompressionEngine.h"
#include "../GPU/GPUTensorAccelerator.h"
#include "../GPU/ShaderModelValidator.h"
#include "../GPU/VulkanRayTracingPreview.h"
#include "../Memory/MemoryBandwidthProfiler.h"
#include "../Memory/MemoryCompressionEngine.h"
#include "../Memory/ZeroCostAbstractionLayer.h"
#include "../Pipeline/AdaptiveBatchCoalescer.h"
#include "../Pipeline/StreamingMipChain.h"
#include "../Pipeline/ThumbnailMorphTransition.h"
#include "../Plugin/PluginTelemetryBridge.h"

// Sprint 349-393: Enhancement Plan V15 — Production Polish
#include "../AI/DirectMLInferenceEngine.h"
#include "../AI/ONNXModelLoader.h"
#include "../Core/AVX2ScaleKernel.h"
#include "../Core/CRTLinkageValidator.h"
#include "../Core/FFmpegExtractor.h"
#include "../Core/FreeTypeRenderer.h"
#include "../Core/InstructionSetRouter.h"
#include "../Core/LENSTypeRegistry.h"
#include "../Core/MuPDFRenderer.h"
#include "../Core/NEONScaleKernel.h"
#include "../Core/OpenJPEGRenderer.h"
#include "../Core/OwnerDrawThemeEngine.h"
#include "../Core/PluginHostSupervisor.h"
#include "../Core/RegistryBatchHandler.h"
#include "../Decoders/JPEG2000DecoderV2.h"
#include "../Decoders/UniversalVideoDecoder.h"
#include "../GPU/ACESTonemapKernel.h"
#include "../GPU/BicubicResizeKernel.h"
#include "../GPU/ColorConvertKernel.h"
#include "../GPU/LanczosGPUScaler.h"
#include "../GPU/ShaderLibraryManager.h"
#include "../Memory/MemoryCompactionScheduler.h"
#include "../Memory/SIMDMemoryAligner.h"
#include "../Pipeline/FFmpegCodecRouter.h"
#include "../Pipeline/FolderWatchPredictor.h"
#include "../Pipeline/ParallelIOScheduler.h"
#include "../Pipeline/ShellPropertyProvider.h"
#include "../Pipeline/ZeroCopyActivator.h"
#include "../Utils/DPIScalingManager.h"
#include "../Utils/FormatHealthIndicator.h"
#include "../Utils/HighContrastAdapter.h"
#include "../Utils/LivePerformanceTracker.h"
#include "../Utils/SettingsSerializer.h"

// Sprint 394: New feature headers
#include "../Core/ColdStartOptimizer.h"
#include "../GPU/GPUPowerStateManager.h"
#include "../GPU/GPUWorkgroupOptimizer.h"
#include "../Memory/CopyOnWriteBufferPool.h"
#include "../Memory/MemoryMappedThumbnailAtlas.h"
#include "../Pipeline/DecodeCancellationEngine.h"
#include "../Pipeline/RequestDeduplicator.h"

// Sprint 395+: Enhancement Plan V15 — 50 New Feature Headers
#include "../AI/FileTypePredictor.h"
#include "../Cache/CacheGarbageCollector.h"
#include "../Cache/CachePartitionManager.h"
#include "../Core/ExplorerIntegrationMonitor.h"
#include "../Core/FileChangeThrottler.h"
#include "../Core/FileConcurrencyGuard.h"
#include "../Core/GlobalShortcutManager.h"
#include "../Core/ResourceThrottlePolicy.h"
#include "../Core/SmartThumbnailPrioritizer.h"
#include "../Decoders/ArchivePeekDecoder.h"
#include "../Decoders/CacheFriendlyDecoder.h"
#include "../Decoders/ContainerInspector.h"
#include "../Decoders/EfficientResizeDecoder.h"
#include "../Decoders/MetadataOnlyDecoder.h"
#include "../Decoders/MultiFormatBatchDecoder.h"
#include "../Decoders/WICFallbackDecoder.h"
#include "../GPU/AdaptiveShaderSelection.h"
#include "../GPU/ComputeShaderProfiler.h"
#include "../GPU/GPUDeviceSelector.h"
#include "../GPU/GPUErrorRecovery.h"
#include "../GPU/GPUFeatureProbe.h"
#include "../Memory/MemoryWatermarkTracker.h"
#include "../Memory/PoolAllocatorMetrics.h"
#include "../Memory/ScopedMemoryBudget.h"
#include "../Memory/StackAllocator.h"
#include "../Memory/ThreadLocalPoolAllocator.h"
#include "../Pipeline/ChunkedDecodeEngine.h"
#include "../Pipeline/DecodeProfilingHarness.h"
#include "../Pipeline/ExplorerQueryOptimizer.h"
#include "../Pipeline/LazyDecodeInitializer.h"
#include "../Pipeline/ThumbnailMergeEngine.h"
#include "../Utils/LogAnalyzer.h"
#include "../Utils/PerformanceReportGenerator.h"
#include "../Utils/RegistryRepairTool.h"
#include "../Utils/SystemInfoCollector.h"

// Sprint 396 headers
// Core
#include "../Core/DecoderPoolManager.h"
#include "../Core/ExplorerNavigationMonitor.h"
#include "../Core/FileSystemJournalReader.h"
#include "../Core/FileTypeAssociationBroker.h"
#include "../Core/IncrementalDecodeEngine.h"
#include "../Core/ProcessIsolationBroker.h"
#include "../Core/WindowsNotificationManager.h"
// Pipeline
#include "../Pipeline/ConcurrentDecodeBarrier.h"
#include "../Pipeline/DecodeWorkDistributor.h"
#include "../Pipeline/FormatSpecificPipeline.h"
#include "../Pipeline/PipelineFusionOptimizer.h"
#include "../Pipeline/PipelineTelemetrySink.h"
#include "../Pipeline/RateLimitedDecodeQueue.h"
#include "../Pipeline/ThumbnailInvalidationTracker.h"
// GPU
#include "../GPU/GPUBatchSubmitter.h"
#include "../GPU/GPUFenceOrchestrator.h"
#include "../GPU/GPUResourceLeakDetector.h"
#include "../GPU/GPUThermalMonitor.h"
#include "../GPU/GPUVendorCapabilityMap.h"
#include "../GPU/ShaderPermutationManager.h"
// Cache
#include "../Cache/CacheReplicationEngine.h"
// Memory
#include "../Memory/AllocatorBenchmark.h"
#include "../Memory/MemoryCompactionEngine.h"
#include "../Memory/WorkingSetOptimizer.h"
// AI
// Plugin
#include "../Plugin/PluginStatePersistence.h"
// Decoders
#include "../Decoders/ClipboardImageDecoder.h"
#include "../Decoders/CompoundDocumentDecoder.h"
#include "../Decoders/ScreenshotAnalyzer.h"
#include "../Decoders/StreamingVideoDecoder.h"
// Utils
#include "../Utils/BuildArtifactValidator.h"
#include "../Utils/WindowsEventLogWriter.h"
// Sprint 397: Enhancement Plan V15 — Phase 2
// Utils
// Core
// Pipeline
// GPU
#include "../GPU/GPUCommandBundler.h"
#include "../GPU/GPUTimestampProfiler.h"
#include "../GPU/HDRMetadataParser.h"
#include "../GPU/LanczosKernelOptimizer.h"
#include "../GPU/ShaderWarmupEngine.h"
// Cache
// Memory
#include "../Memory/AddressSpaceReserver.h"
#include "../Memory/BitmapPoolPartitioner.h"
#include "../Memory/CommitChargeTracker.h"
// Decoders
#include "../Decoders/FFmpegDemuxerBridge.h"
#include "../Decoders/FreeTypeLayoutEngine.h"
#include "../Decoders/MemoryMappedBitmapReader.h"
#include "../Decoders/OpenJPEGStreamDecoder.h"
// Plugin
#include "../Plugin/PluginHealthReporter.h"
// Sprint 398 — EP V15 Phase 3
// Core
#include "../Core/AsyncRegistrySnapshot.h"
#include "../Core/BatchAbortController.h"
#include "../Core/ContextMenuFormatter.h"
#include "../Core/DecoderFallbackChain.h"
#include "../Core/ExtensionConflictDetector.h"
#include "../Core/FileVersionTracker.h"
#include "../Core/OutputColorSpaceMapper.h"
#include "../Core/ProgressReportAggregator.h"
// Pipeline
#include "../Pipeline/AdaptiveChunkSizer.h"
#include "../Pipeline/DecodeQueueInspector.h"
#include "../Pipeline/DecodeWatermarkStamper.h"
#include "../Pipeline/ExtractorPoolBalancer.h"
#include "../Pipeline/IOCompletionPortBridge.h"
#include "../Pipeline/PipelineBackpressureValve.h"
#include "../Pipeline/PipelineTelemetryEmitter.h"
#include "../Pipeline/StreamingMipGenerator.h"
// GPU
#include "../GPU/GPUBarrierOptimizer.h"
#include "../GPU/GPUVendorQuirksTable.h"
#include "../GPU/ShaderCompileListener.h"
#include "../GPU/ShaderVariantSelector.h"
#include "../GPU/TextureSamplerCache.h"
// Cache
#include "../Cache/CacheSerializationCodec.h"
// Memory
#include "../Memory/HeapFragmentationProbe.h"
#include "../Memory/MemoryBudgetNegotiator.h"
#include "../Memory/MemoryTrimPolicy.h"
#include "../Memory/VirtualAllocTracker.h"
// Decoders
#include "../Decoders/ColorProfileValidator.h"
#include "../Decoders/DecoderCapabilityProbe.h"
#include "../Decoders/ExifThumbnailExtractor.h"
#include "../Decoders/MultiFrameDecodeRouter.h"
#include "../Decoders/ProgressiveDecodeStreamer.h"
// Plugin
#include "../Plugin/PluginEventBus.h"
#include "../Plugin/PluginFeatureToggle.h"
#include "../Plugin/PluginSchemaValidator.h"
// Utils
#include "../Utils/DeploymentVerifier.h"
#include "../Utils/FeatureFlagRegistry.h"
#include "../Utils/StartupTimingProfiler.h"
// Sprint 399 — EP V15 Phase 4
#include "../Core/ConcurrentExtractScheduler.h"
#include "../Core/ContextualPreviewEngine.h"
#include "../Core/FileSizeEstimator.h"
#include "../Core/FileSystemWatchdog.h"
#include "../Decoders/AnimatedFormatDecoder.h"
#include "../Decoders/ContainerPreviewDecoder.h"
#include "../Decoders/EmbeddedThumbnailDecoder.h"
#include "../Decoders/MultipageDocumentDecoder.h"
#include "../Decoders/SidecarMetadataDecoder.h"
#include "../GPU/ComputeDispatchOptimizer.h"
#include "../GPU/GPUFormatConverter.h"
#include "../GPU/GPUOccupancyCalculator.h"
#include "../GPU/GPUTextureMipChain.h"
#include "../GPU/GPUThumbnailCompositor.h"
#include "../GPU/ShaderHotReloader.h"
#include "../Memory/BitmapMemoryRecycler.h"
#include "../Memory/MemoryAllocationTracer.h"
#include "../Memory/MemoryPressureResponder.h"
#include "../Memory/NUMANodeAllocator.h"
#include "../Memory/ZeroFragmentationHeap.h"
#include "../Pipeline/AdaptivePipelineScheduler.h"
#include "../Pipeline/DecodeThroughputRegulator.h"
#include "../Pipeline/MemoryMappedPipelineStage.h"
#include "../Pipeline/PipelineLatencyTracker.h"
#include "../Pipeline/PipelineLoadShedder.h"
#include "../Pipeline/StreamingThumbnailEmitter.h"
// Sprint 261-270 (v20.6.0 "Quasar-W") — Plugin Marketplace v2
#include "../Plugin/PluginInstaller.h"
#include "../Plugin/PluginPackageManifest.h"
#include "../Plugin/PluginSearchIndex.h"
// Sprint 271-280 (v20.7.0 "Quasar-X") — Observability v2
#include "../Core/DiagnosticsConsole.h"
#include "../Core/LatencyBudgetManager.h"
#include "../Core/NetworkAwarePrefetcher.h"
#include "../Utils/AutoUpdateManager.h"
#include "../Utils/CrashReporter.h"
#include "../Utils/FeatureFlagManager.h"
#include "../Utils/UsageStats.h"
// Sprint 281-290 (v21.0.0 "Rigel") — Format Expansion III
#include "../Decoders/AVIFSequenceDecoder.h"
#include "../Decoders/HEIFBurstDecoder.h"
#include "../Decoders/JXLAnimationDecoder.h"
#include "../Decoders/PSDLayerDecoder.h"
#include "../Decoders/SVGRasterizer.h"
#include "../Decoders/WebPAnimationDecoder.h"
// Sprint 291-300 (v21.1.0 "Rigel-R") — Advanced GPU Compute v2
#include "../Core/BatchDecodeScheduler.h"
#include "../Core/SIMDImageProcessor.h"
#include "../Core/ThreadPoolV2.h"
#include "../Core/ZeroCopyTextureUploader.h"
#include "../GPU/D3D11DPIAdapter.h"
#include "../GPU/DirectStorageLoader.h"
#include "../GPU/VulkanComputeAccelerator.h"
#include "../GPU/VulkanComputeDecoder.h"
// Sprint 301-310 (v21.2.0 "Rigel-S") — Enterprise Policy v2
#include "../Core/ACLManager.h"
#include "../Core/AuditLogger.h"
#include "../Core/CodeIntegrityChecker.h"
#include "../Core/EnterprisePolicyEngineV2.h"
#include "../Core/FIPSComplianceMode.h"
#include "../Core/IntegrityVerifier.h"
#include "../Core/PrivilegeElevationGuard.h"
#include "../Core/SandboxEscapeGuard.h"
// Sprint 311-320 (v21.3.0 "Rigel-T") — Storage & Caching v3
#include "../Core/PredictivePrefetcher.h"
#include "../Utils/ActivationService.h"
#include "../Utils/FeatureCompatMatrix.h"
#include "../Utils/MemoryMappedLoader.h"
// Sprint 321-330 (v22.0.0 "Sirius" MAJOR) — Cross-Platform Foundation
#include "../Core/ColorBlindnessFilter.h"
#include "../Core/DisplayColorProfile.h"
#include "../Core/FeedbackManager.h"
#include "../Core/KeyboardNavigationHandler.h"
#include "../Core/MonitorConfigWatcher.h"
// Sprint 331-340 (v22.1.0 "Sirius-R") — Performance Profiling v2
#include "../Core/CodecPlatformV2.h"
#include "../Core/InputValidator.h"
#include "../Core/NetworkTrustManager.h"
#include "../Core/ResponsiveLayoutManager.h"
#include "../Core/SecureDecodeContext.h"
#include "../Core/SecureStringPool.h"
#include "../Core/StackGuardPolicy.h"
// Sprint 341-350 (v22.2.0 "Sirius-S") — Security & Audit v3
#include "../AI/BlurDetectionFilter.h"
#include "../Utils/CertificatePinner.h"
#include "../Utils/ColorBlindFilter.h"
#include "../Utils/FirstRunExperience.h"
#include "../Utils/LicenseManager.h"
#include "../Utils/LocalizationEngine.h"
#include "../Utils/LocalizationValidator.h"
#include "../Utils/StoreReadinessChecker.h"
// Sprint 351-360 (v22.3.0 "Sirius-T") — AI Inference Pipeline v2
#include "../AI/AIModelRegistry.h"
#include "../AI/AIPerformanceProfiler.h"
#include "../AI/AIThumbnailPipeline.h"
#include "../AI/AIUpscaler.h"
// Sprint 361-370 — Advanced Scheduling & Concurrency v2 (v22.4.0)
#include "../Core/CPUAffinityRouter.h"
#include "../Core/CooperativeTaskScheduler.h"
#include "../Core/LockFreeMPMCQueue.h"
#include "../Core/RealtimePriorityEngine.h"
#include "../Core/ThreadLocalContextPool.h"
#include "../Core/WorkStealingSchedulerV2.h"
#include "../Memory/HazardPointerReclaimer.h"
#include "../Pipeline/AdaptiveConcurrencyLimiter.h"
// Sprint 371-380 — Format Expansion IV (v22.5.0)
#include "../Decoders/ILBMDecoder.h"
#include "../Decoders/JBIG2Decoder.h"
#include "../Decoders/JNGDecoder.h"
#include "../Decoders/JPEGXTDecoder.h"
#include "../Decoders/QOIRDecoder.h"
#include "../Decoders/SunRasterDecoder.h"
#include "../Decoders/TIFFMultiFrameDecoderV2.h"
// Sprint 381-390 — Windows Shell Integration v2 (v22.6.0)
#include "../Core/DragDropPreviewEngine.h"
#include "../Core/ExplorerColumnProviderV2.h"
#include "../Core/NamespaceWalkEngine.h"
#include "../Core/SearchIndexBridge.h"
// Sprint 391-400 — DevOps & Quality Engineering v2 (v22.7.0)
#include "../Utils/ArtifactIntegrityMonitor.h"
#include "../Utils/BuildTimingAnalytics.h"
#include "../Utils/CIEnvironmentValidator.h"
#include "../Utils/CycloneDXSBOMGenerator.h"
#include "../Utils/MutationTestingEngine.h"
#include "../Utils/PropertyBaseTestEngine.h"
#include "../Utils/RegressionFingerprintEngine.h"
#include "../Utils/ReproducibleBuildVerifierV2.h"
// Sprint 401-410 — Reactive Pipeline Architecture (v23.0.0)
#include "../Pipeline/CQRSThumbnailPipeline.h"
#include "../Pipeline/DomainEventBus.h"
#include "../Pipeline/ReactiveAPIGateway.h"
#include "../Pipeline/ReactiveStreamEngine.h"
#include "../Pipeline/SnapshotStoreEngine.h"
#include "../Pipeline/ThumbnailEventStore.h"
#include "../Pipeline/ThumbnailSagaOrchestrator.h"
// Sprint 411-420 — GPU Acceleration v3 (v23.1.0)
#include "../GPU/AsyncDMACopyEngine.h"
#include "../GPU/CUDATextureDecoder.h"
#include "../GPU/GPUMemoryDefragmenterV2.h"
#include "../GPU/GPUResourceAliasingManager.h"
#include "../GPU/GPUTextureAtlasBuilder.h"
#include "../GPU/GPUThumbnailAtlasManager.h"
#include "../GPU/HIPComputeBackend.h"
#include "../GPU/MultiGPULoadBalancerV3.h"
// Sprint 421-430 — Plugin Ecosystem v3 (v23.2.0)
// Sprint 431-440 — Memory Optimization v3 (v23.3.0)
#include "../Memory/ECCErrorDetector.h"
#include "../Memory/MemoryMappedBTree.h"
#include "../Memory/MemoryOptimizationV3.h"
#include "../Memory/NVMeMemoryTier.h"
#include "../Memory/PressureForecaster.h"
#include "../Memory/SharedMemoryRegionManager.h"
// Sprint 441-450 — Smart Cache v4 (v23.4.0)
#include "../Cache/AIEvictionPolicyEngine.h"
// Sprint 451-460 — CLI & Automation v2 (v23.5.0)
#include "../Utils/DiagnosticBundleCollector.h"
#include "../Utils/RegressionTestRunner.h"

// Sprint 1031-1040 — Decoder Health & Format Management (v31.1.0 "Achernar-R")
#include "../Core/CrashIntelligence.h"
#include "../Core/DecoderHealthDashboard.h"
#include "../Core/DecoderHealthMonitor.h"
#include "../Core/DecoderPriorityManager.h"
#include "../Core/FormatGalleryView.h"
#include "../Core/FormatGroupManager.h"
#include "../Plugin/PluginHostIPC.h"
#include "../Plugin/PluginRuntimeValidation.h"

// Sprint 1071-1080 — Contextual Intelligence & Self-Healing (v31.4.0 "Achernar-U")
#include "../AI/ContextualRenderingEngine.h"
#include "../AI/FormatComplexityAnalyzer.h"
#include "../AI/SmartThumbnailCompositor.h"
#include "../Core/DecoderFaultIsolator.h"
#include "../Core/DiagnosticTelemetryCollector.h"
#include "../Core/FaultTolerantDecodeOrchestrator.h"
#include "../Pipeline/PipelineHealthMonitor.h"
#include "../Pipeline/SmartRetryOrchestrator.h"

// Sprint 1081-1090 — Format Routing & Enhanced Accessibility (v31.5.0 "Achernar-V")
#include "../AI/AdaptiveColorProfileManager.h"
#include "../AI/ThumbnailAccessibilityEngine.h"
#include "../Core/CrossFormatMetadataEngine.h"
#include "../Core/DecoderVersionManager.h"
#include "../Core/SmartFileTypeRouter.h"
#include "../Pipeline/RenderPipelineProfiler.h"
#include "../Pipeline/StreamingDecodeCoordinator.h"

#include <chrono>
// Compatibility macro for ASSERT_EQUAL(expected, actual) → ASSERT((a) == (b))
#define ASSERT_EQUAL(a, b) ASSERT((a) == (b))
#include <psapi.h>
#include <iostream>

#pragma comment(lib, "psapi.lib")
#include <cassert>
#include <cstring>
#include <string>
#include <vector>

// GPU tests
extern void RunGPUTests();

using namespace ExplorerLens::Engine;

// Sprint S231-S237 (ROADMAP v6.0 Phase 1) headers under test
#include <thread>
#include "../Core/LensFormatsCommand.h"
#include "../Core/NodiscardMacros.h"
#include "../Core/COMBoundaryGuard.h"
#include "../Core/ProbeCache.h"
#include "../Cache/CacheKeyV2.h"
#include "../Core/STAComplianceGuard.h"
#include "../Cache/CacheBlobFormatV1.h"

// Sprint S241-S249 (ROADMAP v6.0 Phase 1/2) scaffolds under test
#include "../Core/PixelSpan2D.h"
#include "../Core/DecodeCancelToken.h"
#include "../Core/SSIMValidator.h"
#include "../Core/CorpusManifestV2.h"
#include "../Core/StreamingDecoderV2.h"
#include "../Core/CETCompatibility.h"
#include "../Core/SALAnnotations.h"
#include "../Decoders/PDFiumDecoderStub.h"
#include "../GPU/D3D11ResizePipeline.h"

// Sprint S251-S259 (ROADMAP v6.0 Phase 2) scaffolds under test
#include "../Cache/SqliteThumbnailSchema.h"
#include "../Core/PixelPipeline16Bit.h"
#include "../Core/ExifAutoRotatePolicy.h"
#include "../Pipeline/AsyncPlaceholderStage.h"
#include "../Decoders/TiledTiffReaderStub.h"
#include "PropertyTestGenerators.h"
#include "../Decoders/LibPngDecoderStub.h"
#include "../Decoders/LibTiffDecoderStub.h"
#include "../Decoders/OpenEXR3DecoderStub.h"

// Sprint S261-S269 (ROADMAP v6.0 Phase 3) Shell + decoder contracts
#include "../Core/ShellPreviewHandlerContract.h"
#include "../Core/ShellPropertyStoreContract.h"
#include "../Core/ShellContextMenuContract.h"
#include "../Decoders/SvgResvgDecoderStub.h"
#include "../Decoders/MediaFoundationKeyframeStub.h"
#include "../Decoders/FreeTypeFontSpecimenStub.h"
#include "../Decoders/TinyGltfModelDecoderStub.h"
#include "../Plugin/PluginTrustChainValidatorV1.h"
#include "../Pipeline/FolderCoverImageStage.h"

// Sprint S271-S279 (ROADMAP v6.0 Phase 3) GPU / color / HDR / privacy
#include "../GPU/GpuVendorRoutingContract.h"
#include "../Core/IccColorPipelineContract.h"
#include "../Decoders/AnimatedImagePlaybackContract.h"
#include "../Pipeline/ArchiveNestingGuardStage.h"
#include "../Core/DecoderWatchdogCoordinator.h"
#include "../Core/TelemetryPrivacyRedactor.h"
#include "../Core/Hdr10ToneMappingContract.h"
#include "../Core/ClipboardIntegrationContract.h"
#include "../Core/AccessibilityDescriptorContract.h"

// Sprint S281-S289 (ROADMAP v6.0 Phase 3/4) shell / plugin / WER / enterprise
#include "../Core/SpacebarPreviewShortcutContract.h"
#include "../Plugin/PluginManifestSchemaContract.h"
#include "../Core/LiveEtwSessionContract.h"
#include "../Core/ShellComHostInTestContract.h"
#include "../Core/WinUI3EvaluationGateContract.h"
#include "../Plugin/AppContainerPluginHostContract.h"
#include "../Core/EvCodeSigningPipelineContract.h"
#include "../Core/WerCrashReporterContract.h"
#include "../Enterprise/AdmxGroupPolicySchemaContract.h"
#include "../Core/LensRestApiEndpointContract.h"
#include "../Core/SqlitePHashIndexContract.h"
#include "../Core/CrashTelemetryConsentContract.h"
#include "../Decoders/ArchiveFileBadgeOverlayContract.h"
#include "../Core/MtlsRestAuthContract.h"
#include "../Core/EngineDllAbiContract.h"
#include "../GPU/VulkanResizePipelineContract.h"
#include "../Platform/DbusThumbnailerContract.h"
#include "../Plugin/PluginCatalogSchemaContract.h"

// Sprint S301-S310 — ROADMAP v7.0 Phase 1 Foundation Cleanup
#include "../Core/StbImageAuditContract.h"
#include "../Core/AsyncDecodeToken.h"
#include "../Core/EmbeddedJpegExtractor.h"
#include "../Codec/IccProfileManager.h"

#include "EngineTestsMacros.h"
