// APIReferenceGenerator.h — Engine API Reference Generator
// Copyright (c) 2026 ExplorerLens Project
//
// Generates API reference documentation from engine headers.
// Produces structured output for each public class, method, enum,
// and struct. Integrates with Doxygen config generation.

#pragma once

#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

namespace ExplorerLens {
namespace Engine {

/// API visibility
enum class APIVisibility : uint8_t {
    Public    = 0,   ///< Part of public API
    Internal  = 1,   ///< Engine-internal
    Plugin    = 2,   ///< Plugin SDK API
    COM       = 3    ///< COM interface
};

/// API stability
enum class APIStability : uint8_t {
    Stable    = 0,   ///< Backward-compatible, versioned
    Beta      = 1,   ///< May change in future versions
    Experimental = 2, ///< Subject to removal
    Deprecated = 3   ///< Will be removed
};

/// API entry for documentation
struct APIEntry {
    const char* className = nullptr;
    const char* methodName = nullptr;
    const char* signature = nullptr;
    const char* description = nullptr;
    const char* returnType = nullptr;
    const char* since = nullptr;         ///< e.g., "v15.0.0"
    APIVisibility visibility = APIVisibility::Public;
    APIStability stability = APIStability::Stable;
    const char* headerFile = nullptr;
};

/// Doxygen configuration
struct DoxygenConfig {
    const char* projectName = "ExplorerLens Engine";
    const char* projectVersion = "15.0.0";
    const char* projectBrief = "GPU-Accelerated Thumbnail Provider for Windows Shell";
    const char* inputDirs = "Engine/ LENSShell/ SDK/";
    const char* outputDir = "docs/api";
    const char* excludePatterns = "*/external/* */build/* */gtest/*";
    bool generateHTML = true;
    bool generateLatex = false;
    bool generateXML = true;
    bool extractAll = false;
    bool extractPrivate = false;
    bool callGraph = true;
    bool callerGraph = true;
    const char* theme = "doxygen-awesome-css";
};

/// API reference generator
class APIReferenceGenerator {
public:
    static APIReferenceGenerator& Instance() {
        static APIReferenceGenerator inst;
        return inst;
    }

    /// Generate Doxyfile configuration
    bool GenerateDoxyfile(const wchar_t* outputPath,
                           const DoxygenConfig& config = {}) {
        FILE* fp = nullptr;
        _wfopen_s(&fp, outputPath, L"w");
        if (!fp) return false;

        fprintf(fp, "# Doxyfile — Auto-generated by ExplorerLens APIReferenceGenerator\n\n");
        fprintf(fp, "PROJECT_NAME           = \"%s\"\n", config.projectName);
        fprintf(fp, "PROJECT_NUMBER         = \"%s\"\n", config.projectVersion);
        fprintf(fp, "PROJECT_BRIEF          = \"%s\"\n", config.projectBrief);
        fprintf(fp, "OUTPUT_DIRECTORY       = %s\n", config.outputDir);
        fprintf(fp, "INPUT                  = %s\n", config.inputDirs);
        fprintf(fp, "EXCLUDE_PATTERNS       = %s\n", config.excludePatterns);
        fprintf(fp, "RECURSIVE              = YES\n");
        fprintf(fp, "FILE_PATTERNS          = *.h *.cpp *.hlsl\n");
        fprintf(fp, "GENERATE_HTML          = %s\n", config.generateHTML ? "YES" : "NO");
        fprintf(fp, "GENERATE_LATEX         = %s\n", config.generateLatex ? "YES" : "NO");
        fprintf(fp, "GENERATE_XML           = %s\n", config.generateXML ? "YES" : "NO");
        fprintf(fp, "EXTRACT_ALL            = %s\n", config.extractAll ? "YES" : "NO");
        fprintf(fp, "EXTRACT_PRIVATE        = %s\n", config.extractPrivate ? "YES" : "NO");
        fprintf(fp, "CALL_GRAPH             = %s\n", config.callGraph ? "YES" : "NO");
        fprintf(fp, "CALLER_GRAPH           = %s\n", config.callerGraph ? "YES" : "NO");
        fprintf(fp, "HAVE_DOT               = YES\n");
        fprintf(fp, "DOT_IMAGE_FORMAT       = svg\n");
        fprintf(fp, "INTERACTIVE_SVG        = YES\n");
        fprintf(fp, "SOURCE_BROWSER         = YES\n");
        fprintf(fp, "INLINE_SOURCES         = NO\n");
        fprintf(fp, "STRIP_FROM_PATH        = ..\n");
        fprintf(fp, "OPTIMIZE_OUTPUT_FOR_C  = NO\n");
        fprintf(fp, "BUILTIN_STL_SUPPORT    = YES\n");
        fprintf(fp, "\n# C++20 support\n");
        fprintf(fp, "CLANG_ASSISTED_PARSING = NO\n");
        fprintf(fp, "CPP_CLI_SUPPORT        = NO\n");
        fprintf(fp, "\n# Theme\n");
        fprintf(fp, "HTML_EXTRA_STYLESHEET  = %s/doxygen-awesome.css\n", config.theme);
        fprintf(fp, "HTML_COLORSTYLE        = LIGHT\n");
        fclose(fp);
        return true;
    }

    /// Register an API entry
    void RegisterAPI(const APIEntry& entry) {
        m_entries.push_back(entry);
    }

    /// Generate API summary markdown
    bool GenerateAPISummary(const wchar_t* outputPath) {
        FILE* fp = nullptr;
        _wfopen_s(&fp, outputPath, L"w");
        if (!fp) return false;

        fprintf(fp, "# ExplorerLens Engine API Reference\n\n");
        fprintf(fp, "**Version:** 15.0.0 \"Zenith\"\n\n");
        fprintf(fp, "## Public API\n\n");
        fprintf(fp, "| Class | Method | Since | Stability |\n");
        fprintf(fp, "|-------|--------|-------|----------|\n");

        for (const auto& e : m_entries) {
            if (e.visibility == APIVisibility::Public) {
                fprintf(fp, "| %s | %s | %s | %s |\n",
                        e.className ? e.className : "-",
                        e.methodName ? e.methodName : "-",
                        e.since ? e.since : "-",
                        StabilityName(e.stability));
            }
        }

        fprintf(fp, "\n## Plugin SDK API\n\n");
        fprintf(fp, "| Class | Method | Since | Stability |\n");
        fprintf(fp, "|-------|--------|-------|----------|\n");

        for (const auto& e : m_entries) {
            if (e.visibility == APIVisibility::Plugin) {
                fprintf(fp, "| %s | %s | %s | %s |\n",
                        e.className ? e.className : "-",
                        e.methodName ? e.methodName : "-",
                        e.since ? e.since : "-",
                        StabilityName(e.stability));
            }
        }

        fclose(fp);
        return true;
    }

    /// Count APIs by stability
    uint32_t CountByStability(APIStability s) const {
        uint32_t c = 0;
        for (const auto& e : m_entries)
            if (e.stability == s) ++c;
        return c;
    }

    static const char* StabilityName(APIStability s) {
        switch (s) {
            case APIStability::Stable:       return "Stable";
            case APIStability::Beta:         return "Beta";
            case APIStability::Experimental: return "Experimental";
            case APIStability::Deprecated:   return "Deprecated";
            default:                          return "Unknown";
        }
    }

    const std::vector<APIEntry>& GetEntries() const { return m_entries; }

private:
    APIReferenceGenerator() = default;
    std::vector<APIEntry> m_entries;
};

} // namespace Engine
} // namespace ExplorerLens
